apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ name }}
  labels:
    app: {{ name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-client
      version: v2
  template:
    metadata:
      labels:
        app: {{ name }}
        version: v2
    spec:
      containers:
        - name: {{ name }}
          image: {{ image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ port }}
          env:
            - name: REACT_APP_BASE_URL
              value: "$(route)"
